name: "S3 Upload Basic"
description: "Upload files and directories to S3 compatible cloud buckets"
author: "Drew Blake <drew@dmblake.com>"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: message-square
  color: gray-dark
